{{- range .Values.consul.configMaps.namespaces }}
{{- $rangeItem := . -}}
{{- with $ }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "consul-autoencrypt-k8s.fullname" . }}
  labels:
    {{- include "consul-autoencrypt-k8s.labels" . | nindent 4 }}
  namespace: {{ $rangeItem }}
roleRef:
    kind: Role
    name: {{ include "consul-autoencrypt-k8s.fullname" . }}
    apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: {{ include "consul-autoencrypt-k8s.fullname" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}
{{- end }}
