apiVersion: v1
kind: Pod
metadata:
  name: "{{ .Release.Name }}-creation-test"
  annotations:
    "helm.sh/hook": test,post-install,post-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
  labels:
    {{- include "consul-autoencrypt-k8s.labels" . | nindent 4 }}
spec:
  restartPolicy: Never
  {{- with .Values.nodeSelector }}
  nodeSelector:
    {{- toYaml . | nindent 8 }}
  {{- end }}
  {{- with .Values.affinity }}
  affinity:
    {{- toYaml . | nindent 8 }}
  {{- end }}
  {{- with .Values.tolerations }}
  tolerations:
    {{- toYaml . | nindent 8 }}
  {{- end }}
  {{- with .Values.imagePullSecrets }}
  imagePullSecrets:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  serviceAccountName: {{ include "consul-autoencrypt-k8s.serviceAccountName" . }}
  securityContext:
    {{- toYaml .Values.podSecurityContext | nindent 4 }}
  containers:
    - name: test
      image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
      command:
        - /bin/sh
        - -ec
        - |
          mkdir -p /tmp \
            && echo {{ include "creation_test" . | b64enc }} | \
              base64 -d > /tmp/check.sh \
            && chmod +x /tmp/check.sh \
            && /tmp/check.sh
